FROM python:3.12.0a5-slim-bullseye

RUN apt update && apt install -y curl

WORKDIR /app
COPY requirements.txt .
RUN pip3 install -r ./requirements.txt

COPY . .

ENTRYPOINT ["gunicorn", "app:app", "-w", "2", "-b", "0.0.0.0:80"]
